var express = require("express");
var app = express();
var homeRouter = require('./router/home');
var checkoutRouter = require('./router/checkout');
var cartRouter = require('./router/cart');
var classesRouter = require('./router/classes');
var classDetailRouter = require('./router/classDetail');
var classFormRouter = require('./router/classForm');
var passwordUpdateRouter = require('./router/passwordUpdate');
var productsRouter = require('./router/products');
var productDetailRouter = require('./router/productDetail');
var registeredRouter = require('./router/registered');
var userRouter = require('./router/user');
var orderHistoryRouter = require('./router/orderHistory');
var ordersRouter = require('./router/orders');
var aboutRouter = require('./router/about');
app.listen(3000);

app.use(express.json());
app.use(express.static("public"));
app.use(express.urlencoded({ extended: true }));
app.set('view engine', 'ejs');
app.use('/', homeRouter);
app.use('/checkout', checkoutRouter);
app.use('/cart', cartRouter);
app.use('/classes', classesRouter);
app.use('/classDetail', classDetailRouter);
app.use('/classForm', classFormRouter);
app.use('/passwordUpdate', passwordUpdateRouter);
app.use('/products', productsRouter);
app.use('/productDetail', productDetailRouter);
app.use('/registered', registeredRouter);
app.use('/user', userRouter);
app.use('/orderHistory', orderHistoryRouter);
app.use('/orders', ordersRouter);
app.use('/about', aboutRouter);

app.get('/sort', function (req, res) {
  res.render('sort');
});